version: "3.8"

services:
  pig:
    image: suhothayan/hadoop-spark-pig-hive:2.9.2
    container_name: tarea3-pig
    hostname: tarea3-pig
    tty: true
    stdin_open: true
    ports:
      - "9870:9870"
      - "8088:8088"
    volumes:
      - ./data:/workspace/data
      - ./pig_scripts:/workspace/pig_scripts
      - ./scripts:/workspace/scripts
      - ./results:/workspace/results